behaviors:
  Discrete:
    trainer_type: ppo
    hyperparameters:
      buffer_size: 1024
      batch_size: 128
      learning_rate: 0.0003
      beta: 0.01
      beta_schedule: linear
      epsilon: 0.3
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      # memory:
      #   use_recurrent: true
      #   sequence_length: 8
      #   memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1
        network_settings:
          normalize: true
          hidden_units: 512
      curiosity:
        gamma: 0.99
        strength: 1
        network_settings:
          normalize: true
          hidden_units: 512
          num_layers: 2
        learning_rate: 0.0003
      rnd:
        gamma: 0.99
        strength: 1
        network_settings:
          normalize: true
          hidden_units: 512
          learning_rate: 0.0003
          num_layers: 2
      gail:
        gamma: 0.99
        strength: 0.01
        network_settings:
          normalize: true
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: /home/yueqi/DRL/UnityBox5/DRL-RNN-LSTM-BOX-SIM/Assets/ML-Agents/packerhand/Demos/boxpackingdemo00.demo
    keep_checkpoints: 5
    checkpoint_interval: 20000
    time_horizon: 128
    max_steps: 3000000
    summary_freq: 2560
    


  
  # Add this section
environment_parameters:
  discrete:
    curriculum:
      - name: 1MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0
        value: 0.0
      - name: 2MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 500
        value: 1.0
      - name: 3MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 600
        value: 2.0
      - name: 4MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 600
        value: 3.0
      - name: 5MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 700
        value: 4.0
      - name: 6MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 700
        value: 5.0
      - name: 7MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 700
        value: 6.0
      - name: 8MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 7.0
      - name: 9MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 8.0
      - name: 10MixLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 9.0


      
