behaviors:
  Discrete:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.001
      beta: 0.005
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      # curiosity:  # curiosity works only with sparse rewards
      #   gamma: 0.99
      #   strength: 0.02
      #   network_settings:
      #     hidden_units: 256
      #   learning_rate: 0.0003
    keep_checkpoints: 5
    checkpoint_interval: 20000
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 2000
  Continuous:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.001
      beta: 0.005
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      # curiosity:  # curiosity works only with sparse rewards
      #   gamma: 0.99
      #   strength: 0.02
      #   network_settings:
      #     hidden_units: 256
      #   learning_rate: 0.0003
    keep_checkpoints: 5
    checkpoint_interval: 20000
    max_steps: 1000000
    time_horizon: 128 
    summary_freq: 2000

  
  # Add this section
environment_parameters:
  Discrete:
    curriculum:
      - name: Lesson01 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 0.0
      - name: Lesson02 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 1.0
      - name: Lesson03 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 2.0
  Continuous:
    curriculum:
      - name: Lesson01 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Continuous
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 0.0
      - name: Lesson02 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Continuous
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 1.0
      - name: Lesson03 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Continuous
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 2.0     
