behaviors:
  Discrete:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 32
      buffer_size: 2560000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 1
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 1
    summary_freq: 2560

environment_parameters:
  discrete:
    curriculum:
      - name: EasyDiscreteLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 600
        value: 0.0
      - name: MySecondLesson # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 700
          require_reset: true
        value: 1.0
      - name: MyLastLesson
        value: 2.0