behaviors:
  Discrete:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 0.001
      beta: 0.005
      beta_schedule: linear
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 20000
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 2000
  # Mix:
  #   trainer_type: ppo
  #   hyperparameters:
  #     batch_size: 512
  #     buffer_size: 4096
  #     learning_rate: 0.001
  #     beta: 0.005
  #     beta_schedule: linear
  #     epsilon: 0.2
  #     epsilon_schedule: linear
  #     lambd: 0.95
  #     num_epoch: 6
  #     learning_rate_schedule: linear
  #   network_settings:
  #     normalize: true
  #     hidden_units: 256
  #     num_layers: 3
  #     vis_encode_type: simple
  #   reward_signals:
  #     extrinsic:
  #       gamma: 0.995
  #       strength: 1.0
  #   keep_checkpoints: 5
  #   checkpoint_interval: 20000
  #   max_steps: 1000000
  #   time_horizon: 128
  #   summary_freq: 2000
  # Continuous:
  #   trainer_type: ppo
  #   hyperparameters:
  #     batch_size: 512
  #     buffer_size: 4096
  #     learning_rate: 0.001
  #     beta: 0.005
  #     beta_schedule: linear
  #     epsilon: 0.2
  #     epsilon_schedule: linear
  #     lambd: 0.95
  #     num_epoch: 6
  #     learning_rate_schedule: linear
  #   network_settings:
  #     normalize: true
  #     hidden_units: 256
  #     num_layers: 3
  #     vis_encode_type: simple
  #   reward_signals:
  #     extrinsic:
  #       gamma: 0.995
  #       strength: 1.0
  #   keep_checkpoints: 5
  #   checkpoint_interval: 20000
  #   max_steps: 1000000
  #   time_horizon: 128
  #   summary_freq: 2000

  
  # Add this section
environment_parameters:
  discrete:
    curriculum:
      - name: 8BoxDiscreteLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0
        value: 0.0
      - name: 30BoxDiscreteLesson # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Discrete
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 900
        value: 1.0
  # mix:
  #   curriculum:
  #     - name: EasyDiscreteLesson # The '-' is important as this is a list
  #       completion_criteria:
  #         measure: reward
  #         behavior: Mix
  #         signal_smoothing: true
  #         min_lesson_length: 100
  #         threshold: 900
  #       value: 0.0
  #     - name: EasyContinuousLesson # This is the start of the second lesson
  #       completion_criteria:
  #         measure: reward
  #         behavior: Mix
  #         signal_smoothing: true
  #         min_lesson_length: 100
  #         threshold: 500
  #         require_reset: true
  #       value: 1.0
  #     - name: HardContinuousLesson
  #       value: 2.0
  # continuous:
  #   curriculum:
  #     - name: EasyContinuousLesson # This is the start of the second lesson
  #       completion_criteria:
  #         measure: reward
  #         behavior: Continuous
  #         signal_smoothing: true
  #         min_lesson_length: 100
  #         threshold: 500
  #         require_reset: true
  #       value: 1.0
  #     - name: HardContinuousLesson
  #       value: 2.0
      
